bimmer_connected/state.py
Added some head units which also give the right json output
Added a check to see if vehicle tracking is enabled
=> Extra head units and check if vehicle tracking is enabled

.gitignore, README.rst, bimmer_connected/__init__.py, bimmer_connected/state.py, bimmer_connected/vehicle.py, generate_vehicle_fingerprint.py, requirements.txt, setup.py, test/test_state.py, test/test_vehicle.py, tox.ini
* added dependency on typing
* added lids and windows for #17
* added door lock state #17 
* added hasRex and driveTrain
* added generate_vehicle_fingerprint.py
* updated readme to contribute data
@gerard33 can you have a look and see if this is the API for doors, windows and lock you wanted to have?
I also added a `generate_vehicle_fingerprint.py` script to log all responses from the server, so that we can get data for debugging other vehicles
=> added lids, windows, lock and more

bimmer_connected/state.py, test/responses/F48_EntryNav/dynamic.json, test/responses/I01_NBT/dynamic.json, test/test_state.py
as requested in #28:
* added last update reason
* added condition based services
* added parking lights
@gerard33 please review
=> Added more attributes

bimmerconnected
so that we can keep several different recordings of different states
of the vehicle
=> added timestamp to vehicle_fingerprint

.gitignore, bimmer_connected/const.py, bimmer_connected/vehicle.py, bimmerconnected
Added feature to fetch the vehicle image :framed_picture:  from the server. To test it run `bimmerconnected image <user> <password> <vin>`. This will give you a new file `image.png`
I did not add any tests for this one as there is not much code anyways.
@gerard33 
This resolves your request #24 :heavy_check_mark: .
=> added fetching an image of the vehicle

bimmer_connected/state.py
As the data we get from the servers is integers, let's also output them as integers.
The only exception: The GPS position is given as floats.
This reoslves #68.
=> changed output types to int

bimmer_connected/remote_services.py
Simple documentation and logging fix.
=> Documentation and log fix

bimmer_connected/state.py, test/responses/F48/status.json, test/test_state.py
@gerard33 thx for the test data https://github.com/m1n3rva/bimmer_connected/issues/55!
I added it to the data set and also added some tests for Check Control Messages.
=> added test data and tests for check control messages

.coveragerc
as it's not covered by unit tests :)
=> excluding cli.py from unit test coverage

README.rst
I've tried the library with a G20 3 series that has a MGU navi and it works fine.
=> Adapt readme

bimmer_connected/cli.py
=> Fix sending messages from cli

.readthedocs.yml, README.rst, readthedocs.yml, requirements-docs.txt, requirements-test.txt, tox.ini
This PR fixes the failing builds on [https://bimmer-connected.readthedocs.io/](https://bimmer-connected.readthedocs.io/).
=> Fix building on readthedocs.io

bimmer_connected/state.py, bimmer_connected/vehicle.py, test/__init__.py, test/test_vehicle.py
PR #213 to separate branch to create beta release.
=> Select available state services from vehicles list

CONTRIBUTING.md, bimmer_connected/account.py
Fixes automatic merging issue of #225 leading to china login again not possible.
=> Fix automatic merge issues of #225 for china login

bimmer_connected/vehicle_status.py, test/test_vehicle_status.py
=> Added vehicle position-heading

.github/workflows/lock.yml
The lock bot Github app is not working anymore.
=> Replace lock bot with GitHub Action

.github/workflows/stale.yml
The stale bot Github app is not working anymore.
=> Replace stale bot with GitHub Action

.github/workflows/stale.yml
Some improvements after first use
=> Some changes to stale bot

bimmer_connected/vehicle_status.py
there seem to be additional position states, like LAST_KNOWN so changed the bool condition to include DRIVER_DISABLED as actual indication of vehicle tracking being disabled.
- This PR fixes or closes issue: fixes #261 
=> Fix vehicle position states

README.rst
=> Fix Travis badge

.github/release-drafter.yml, bimmer_connected/account.py, bimmer_connected/country_selector.py
Again thanks to @TA2k, login for `north_america` should be fixed now.
- This PR fixes or closes issue: fixes (partly) #298 
- This PR is related to issue: #298
=> Fix My BMW login for north_america

bimmer_connected/account.py, bimmer_connected/country_selector.py, setup.cfg, test/__init__.py, test/test_state.py, test/test_vehicle_status.py
- Revert `china` to Connected Drive login flow
- unsure how long it will continue to work, we have to migrate at some point
- fix new test from `pylint>=2.10.0`
- This PR fixes or closes issue: fixes #313 
=> Fix China & pylint

.coveragerc, bimmer_connected/account.py, bimmer_connected/all_trips.py, bimmer_connected/charging_profile.py, bimmer_connected/efficiency.py, bimmer_connected/last_destinations.py, bimmer_connected/last_trip.py, bimmer_connected/navigation.py, bimmer_connected/range_maps.py, bimmer_connected/remote_services.py, bimmer_connected/state.py, bimmer_connected/vehicle.py, bimmer_connected/vehicle_status.py
* Fix invalid type annotation in `vehicle_status`
* Add self referencing types (guarded by `TYPE_CHECKING`)
* Add some additional annotations
I've split these changes into individual commits to make reviewing them a bit easier.
Noticed most of these while working on https://github.com/home-assistant/core/pull/58506.
=> Fix and improve typing

bimmer_connected/account.py, bimmer_connected/const.py, bimmer_connected/country_selector.py, bimmer_connected/vehicle_status.py, requirements.txt, test/responses/auth/auth_cn_login_error.json, test/responses/auth/auth_cn_login_pwd.json, test/responses/auth/auth_cn_publickey.json, test/test_account.py
Re-enable `china` region again. Thanks for the helpful input @zhaozengxiao and @muxiachuixue!
- This PR fixes or closes issue: fixes #347
=> Enable login to china again

requirements.txt, setup.cfg, setup.py
Loosen dependencies as much as possible as this is needed for Home Assistant (cf. [Comment in home-assistant/core#59881](https://github.com/home-assistant/core/pull/59881/files#discussion_r756349343)).
=> Set minimum dependencies only

bimmer_connected/account.py
Request english language responses for china to be able to map them to our enums (cf. https://github.com/bimmerconnected/bimmer_connected/issues/347#issuecomment-977833052).
=> Force english responses (especially for china)

README.rst
Change badge to check master branch.
=> Update test badge to master

README.rst
- This PR fixes or closes issue: fixes #347 
=> Mention @muxiachuixue's work for china login

bimmer_connected/utils.py, bimmer_connected/vehicle.py, bimmer_connected/vehicle_status.py, requirements.txt, setup.py, test/test_utils.py
Fixes:
* `Retry`-based login strategy by pinning `urllib3>=1.26.5`
* In some cases, `bimmerconnected status` would fail with `ValueError: Circular reference detected`
- This PR fixes or closes issue: fixes #406 
=> Fix cli `fingerprint` and login issues

bimmer_connected/account.py
Always send `dart:io` user-agent when doing HTTP requests that originated from the MyBMW app.
- This PR fixes or closes issue: fixes #408 
=> Always send user-agent header

bimmer_connected/const.py
The original version is too old. BMW API will give an error: "the App version is too old, please update".
Fix the bug warning "MyBMW version is too old, please update"
=> Bump X-User-Agent

.github/workflows/test.yml, .pre-commit-config.yaml, bimmer_connected/cli.py, bimmer_connected/utils.py, bimmer_connected/vehicle/charging_profile.py, bimmer_connected/vehicle/remote_services.py, bimmer_connected/vehicle/vehicle.py, bimmer_connected/vehicle/vehicle_status.py, pyproject.toml, requirements-test.txt, setup.cfg
Last fixes for mypy. Thanks @cdce8p for your initial and tremendous help getting everything in!
When this is merged, we probably don't need #396 anymore, am I correct?
=> Add mypy to pre-commit and test pipeline

bimmer_connected/account.py, bimmer_connected/api/authentication.py, bimmer_connected/api/client.py, bimmer_connected/cli.py, bimmer_connected/const.py, bimmer_connected/vehicle/vehicle.py, test/responses/G21/json_export.json, test/test_account.py
Change user agent to a public Android build number.
- This PR fixes or closes issue: fixes #444 
=> Update user agent

docs/source/conf.py
Fixes docs build with `sphinx==5.0.0`. 
=> Fix sphinx build

bimmer_connected/api/authentication.py, bimmer_connected/api/client.py, bimmer_connected/api/regions.py, bimmer_connected/const.py, bimmer_connected/models.py
Change app version in user agent from `2.5.2` (ROW + NA) to ~~`2.5.0`~~ `2.3.0` (CN). Apparently the 2.5.2 agent got blocked in CN.
- This PR fixes or closes issue: fixes #452
=> Downgrade app version

bimmer_connected/models.py
Fix sending location to car. The API seems to require an empty list for `entryPoints`.
- This PR fixes or closes issue: fixes #455 
=> Fix send location

bimmer_connected/api/client.py, bimmer_connected/cli.py, bimmer_connected/vehicle/vehicle.py
The MyBMW app has switched the vehicle data endpoint. This updates the `fingerprint` function to data from the new ones as well.
=> Fingerprint vehicles v2

bimmer_connected/vehicle/charging_profile.py, test/responses/G21/json_export.json
Allow `climatisationOn` not to exist. Not sure if there are more issue like this.
- This PR fixes or closes issue: fixes #460 
- This PR is related to issue: https://github.com/home-assistant/core/issues/73271
=> Fix KeyError in `ChargingProfile`

bimmer_connected/vehicle/vehicle.py
Add drive train type `MILD_HYBRID` (seems to be renamed in the API) and add both mild hybrid to `COMBUSTION_ENGINE_DRIVE_TRAINS`.
- This PR fixes or closes issue: fixes #464
=> Add `DriveTrainType.MILD_HYBRID`

bimmer_connected/cli.py
Inspired by https://github.com/home-assistant/core/issues/74703#issuecomment-1183378587, this PR adds a `-i`/`--imperial` flag. 
Not sure if the header that we are setting is even followed by the API.
- This PR is related to issue: https://github.com/home-assistant/core/issues/74703#issuecomment-1183378587
=> Add imperial flag to CLI

bimmer_connected/account.py, bimmer_connected/vehicle/vehicle.py, test/test_deprecated_vehicle_status.py, test/test_vehicle_status.py
This is an internal change with no impact on the usage of the library or in Home Assistant (except when patching `get_vehicles()` directly, e.g. for testing purposes).
During development of the tests for https://github.com/home-assistant/core/pull/76613, I had to copy most of the code from `get_vehicles()` to the HA test case due to different testing mechanisms. 
In the library tests, we rely on capturing the HTTP requests and providing the correct answers. However in HA, this would be a lot of doubled development effort, so I just patched `get_vehicles()`, which triggers all requests (including login).
With this PR, one only has to patch `get_vehicles()`, load the vehicle and state responses and then call `add_vehicles()`, without worrying about additional needed keys or of the vehicle …
=> Refactor creation of vehicles from API responses

.github/workflows/test.yml, bimmer_connected/account.py, test/test_account.py
As suggested in https://github.com/home-assistant/core/pull/74871#discussion_r956785356, this PR adds a function that returns the fingerprint files as dictionary (with key = filename and value = API response).
- This PR is related to issue: https://github.com/home-assistant/core/pull/74871#discussion_r956785356
=> Add fingerprint to dict function

bimmer_connected/vehicle/vehicle.py, test/test_vehicle.py
Updates vehicle view enum for images.
- This PR fixes or closes issue: fixes #498 
=> Adjust VehicleViewDirection

bimmer_connected/vehicle/fuel_and_battery.py, test/test_deprecated_vehicle_status.py, test/test_vehicle_status.py
Updates `total_range` logic for hybrid vehicles to the weird API implementation.
See https://github.com/home-assistant/core/issues/85226#issuecomment-1377698300 for more details.
- This PR is related to issue: https://github.com/home-assistant/core/issues/85226
=> Fix total range for hybrid vehicles

bimmer_connected/vehicle/charging_profile.py, bimmer_connected/vehicle/fuel_and_battery.py, test/test_vehicle_status.py
Add charging target and ac charging limit as discussed in https://github.com/bimmerconnected/bimmer_connected/discussions/435.
Will make a HA PR to add the charging mode, charging preference (already available in lib), charging target and ac charging limit.
- This PR is related to issue: #435
=> Add charging target and ac charging limit

bimmer_connected/const.py, test/test_account.py
Updates the app version for all regions and a small URL change for china.
=> Update app version to 3.1.0

bimmer_connected/vehicle/tires.py, bimmer_connected/vehicle/vehicle.py, test/test_vehicle_status.py
Add `vehicle.tires` containing tire pressure and usage.
- This PR is related to issue: #483
=> Add tire status

bimmer_connected/models.py, bimmer_connected/vehicle/remote_services.py, test/test_remote_services.py
Similar to #522, add custom `MyBMWRemoteServiceException` to remote services.
- This PR is related to issue: https://github.com/home-assistant/core/pull/91081#discussion_r1177094374
=> Add custom exception to remote services

bimmer_connected/account.py, bimmer_connected/api/authentication.py, bimmer_connected/const.py
=> Changes from MyBMW 3.3.1

bimmer_connected/account.py, test/test_account.py
Missed out on this: We need the ability to read & write `gcid` from HA.
=> Add Interface required for China login

bimmer_connected/vehicle/tires.py
Follow up to #531 due to https://github.com/home-assistant/core/issues/92550#issuecomment-1555735713.
=> Make tire pressure entirely optional

bimmer_connected/api/authentication.py, bimmer_connected/api/utils.py, test/test_account.py
Update quota handling.
- This PR is related to issue: https://github.com/home-assistant/core/issues/85962#issuecomment-1613846057
=> Update quota exceeded recognition

.github/workflows/test.yml, .readthedocs.yml, README.rst, bimmer_connected/__init__.py, bimmer_connected/tests/common.py, bimmer_connected/tests/conftest.py, bimmer_connected/tests/test_account.py, bimmer_connected/tests/test_remote_services.py, pyproject.toml, requirements-test.txt, requirements.txt, setup.cfg, setup.py
Support for Python 3.7 is removed. As we now support Python 3.12, this library requires Python >= 3.8.
Remove Python 3.7 support due to offical end of life.
- This PR is related to issue: #553
=> Remove support for Python 3.7

bimmer_connected/tests/common.py
Sort mocked vehicles alphabetically to hopefully fix HA tests.
=> Ensure vehicle order in mocked API

.readthedocs.yml, README.rst
=> Fix README & readthedocs build

requirements-test.txt
Temporary Update test requirements to time_machine<2.13.0 due to https://github.com/adamchainz/time-machine/issues/387
Recent up rev of the time_machine library causes test to fail
=> Update test requirements to time_machine<2.13.0

bimmer_connected/api/authentication.py, bimmer_connected/api/client.py, bimmer_connected/api/regions.py, bimmer_connected/const.py
Fixes login to NA and Rest of World when using the full login flow.
- This PR fixes or closes issue: fixes https://github.com/home-assistant/core/issues/101961
=> Update app version to 3.9.0

bimmer_connected/api/authentication.py, bimmer_connected/tests/test_account.py
Overlooked at edge case in #585: Exactly three 429 followed by a 401 will still raise MyBMWAuthError, as the existing loop would be at an end.
This PR changes the following:
- Loop only for 429 and check for 401 afterwards (this also means that 429 > 401 > 429 will throw a MyBMWQuotaError, but this doesn't trigger reauthentication in HA and will recover itself)
- Minor optimizations
- If a request is successful, we don't even check for error handling
- we're running the loop only if the error is a 429
- This PR is related to issue: https://github.com/home-assistant/core/issues/104555
=>  Fix handling 401 after 429 status code - reauthenticate last

README.rst
I've changed the readthedocs to default to stable (i.e. the latest non-preview release) when not accessing it via a specific URL.
This PR reflects the changes for the readme as well.
=> Change readthedocs link to stable

bimmer_connected/vehicle/vehicle.py
Fixes #603 (in combination with #591).
=> Change vehicle FRONTSIDE image

bimmer_connected/api/utils.py
Seen issues with the regex, apparently the Stackoverflow solution is not enough.
=> Update VIN regex

requirements-docs.txt
=> Fix docs requirements

bimmer_connected/api/utils.py
=> Another VIN regex fix

bimmer_connected/cli.py, bimmer_connected/tests/test_cli.py, requirements-test.txt
Add tests for CLI (available at all, `status` and `fingerprint` commands).
=> Add basic CLI tests

.pre-commit-config.yaml, bimmer_connected/cli.py, bimmer_connected/tests/common.py, bimmer_connected/tests/test_cli.py
=> Improve tests and add version in CLI help output

.pre-commit-config.yaml, bimmer_connected/const.py, bimmer_connected/models.py, bimmer_connected/tests/common.py, bimmer_connected/tests/responses/F31/bmw-eadrax-vcs_v4_vehicles_state_WBA00000000000F31.json, bimmer_connected/tests/responses/G01/bmw-eadrax-vcs_v4_vehicles_state_WBA00000000DEMO04.json, bimmer_connected/tests/responses/G20/bmw-eadrax-vcs_v4_vehicles_state_WBA00000000DEMO03.json, bimmer_connected/tests/responses/G26/bmw-eadrax-vcs_v4_vehicles_state_WBA00000000DEMO02.json, bimmer_connected/tests/responses/G70/bmw-eadrax-vcs_v4_vehicles_state_WBA00000000DEMO05.json, bimmer_connected/tests/responses/I20/bmw-eadrax-vcs_v4_vehicles_state_WBA00000000DEMO01.json, bimmer_connected/tests/test_remote_services.py, bimmer_connected/vehicle/remote_services.py, bimmer_connected/vehicle/vehicle.py
Update to MyBMW 4.7.2.
Most changes are regarding remote services - new URLs and a completely refactored send-to-car.
Vehicle state contains some new information, but the old data is still available for now.
=> Updates for MyBMW 4.7.2

bimmer_connected/cli.py, bimmer_connected/models.py, bimmer_connected/tests/test_account.py, bimmer_connected/tests/test_api.py, bimmer_connected/tests/test_cli.py, bimmer_connected/tests/test_remote_services.py, bimmer_connected/tests/test_utils.py, bimmer_connected/tests/test_vehicle.py, bimmer_connected/tests/test_vehicle_status.py, bimmer_connected/utils.py, bimmer_connected/vehicle/fuel_and_battery.py, bimmer_connected/vehicle/remote_services.py, pyproject.toml
=> Fixes for HA mypy, add more lint rules

setup.cfg
The official (SPDX) short identifier for the Apache License 2.0 is `Apache-2.0`.
https://spdx.org/licenses/Apache-2.0.html
=> Update project metadata to use SPDX license identifier

bimmer_connected/vehicle/vehicle.py
Adds additional VehicleViewDirections.
- This PR is related to issue: #660
=> Add additional VehicleViewDirection

docs/source/captcha.rst, docs/source/captcha/north_america.rst, docs/source/captcha/rest_of_world.rst
=> Improve captcha documentation

bimmer_connected/account.py, bimmer_connected/cli.py, bimmer_connected/tests/test_cli.py
Keep session_id across muliple CLI runs. This is closer to HA behavior (session id resets only during HA restart).
- This PR fixes or closes issue: fixes 
- This PR is related to issue: #686, #681
=> Store bmw-session-id for CLI use

bimmer_connected/cli.py, bimmer_connected/tests/test_cli.py, docs/source/captcha.rst
Resets session_id after 14 days to net keep the same for longer.
Also adds a test to verify that the CLI oauth_store file is saved even if an error occurs.
=> Reset session_id after 14 days

bimmer_connected/tests/responses/G01/bmw-eadrax-vcs_v4_vehicles_state_WBA00000000DEMO04.json, bimmer_connected/tests/test_vehicle_status.py, bimmer_connected/vehicle/reports.py
Adds additional attributes to condition based services (next service by distance and time) as well as as string representation of current check control messages.
Both are for use within specific HA sensors.
=> Get next service by distance/time
