bimmerconnected/bimmer_connected

- bimmer_connected/vehicle.py
- status.py
- test/responses/G31_NBTevo/specs.json
- test/test_specs.py
With the "specs" interface you can get your vehicle specifications.
This is the additional output when running "status.py" now:
```json
vehicle specs:
{
"ENGINE_COMPRESSION": "10.2",
"ENGINE_BORE": "82.0",
"TANK_CAPACITY": "68.0",
"PERFORMANCE_TOP_SPEED": "250",
"WEIGHT_MAX": "2440",
"ENGINE_TORQUE_MAX": "350",
"WEIGHT_PERMITTED_LOAD_REAR": "1425",
"WEIGHT_PERMITTED_LOAD_FRONT": "1115",
"ENGINE_CYLINDERS": "4",
"ENGINE_OUTPUT_MAX_KW": "185",
"PERFORMANCE_ACCELERATION": "6.3",
"ENGINE_SPEED_TORQUE_MAX": "1450-4800",
"ENGINE_SPEED_OUTPUT_MAX": "5200-6500",
"ENGINE_STROKE": "94.6",
"WEIGHT_PERMITTED_LOAD": "730",
"ENGINE_OUTPUT_MAX_HP": "252",
"WEIGHT_UNLADEN": "1770",
"ENGINE_VALVES": "4"
}
```
My use case for this: show remaining fuel in % rather than liters. So I need to know how big the …
> added vehicle specs interface

- bimmer_connected/account.py
- bimmer_connected/const.py
- bimmer_connected/remote_services.py
- bimmer_connected/vehicle.py
- remote_light_flash.py
- test/__init__.py
- test/test_remote_services.py
- test/test_specs.py
- test/test_state.py
After the comments on the PR in Home Assistant (https://github.com/home-assistant/home-assistant/pull/12591), here's a proposal to a new API for the remote services:
* The call to e.g. trigger_remote_door_lock now blocks until we get a final answer from the server. Note: this might take some time.
* If the vehicle state is expected to change after the call: an update of the vehicle state is triggered after a call to the remote services.
* The account now offers a listener to subscribe to vehicle state changes. This is necessary so that we can notify all listeners after an updated is triggered by a call to a remote service
* I incremented the version number, as this is a breaking API change.
* Added horn and climate control as remote services. :warning: I could not yet test these on a live …
> Changed API for remote services

- .gitignore
- bimmer_connected/account.py
- bimmer_connected/const.py
- bimmer_connected/country_selector.py
- bimmer_connected/remote_services.py
- bimmer_connected/state.py
- bimmer_connected/vehicle.py
- generate_vehicle_fingerprint.py
- remote_light_flash.py
- status.py
- test/test_account.py
- test/test_country_selector.py
- test/test_remote_services.py
- test/test_specs.py
- test/test_state.py
- test/test_vehicle.py
I checked out the code in #40 :+1: and the implementation at https://github.com/edent/BMW-i-Remote/ :+1: and did a refactoring to use this API in this library.
We could use the `b2vapi.*` urls to connect to the BMW servers and get the data. I guess this is what the smartphone apps are doing. This way we do not have to care about the different countries.
Maybe only differentiate between :us: , :canada: and the rest of the world. [The readme here](https://github.com/frankjoke/iobroker.bmw) lists also a url for China.
The interfaces on the server side are similar but not identical so I had to change several places. Now `status.py` and `remote_light_flash.py` are working for me (in Europe :eu: ) again. But most of the tests are broken, because the test data is now outdated.
Maybe this would …
> using different urls "b2vapi.bmwgroup.com"

- bimmer_connected/account.py
- test/__init__.py
- test/test_account.py
@lawtancool 
How about this solution for the issue in #45? We already have the server-url contain the string you wanted.
In Europe the `host` part of the header seems to be ignored. So `.us` works just as well as `.com`. Even no `host` works just as well...
> made hostname in header configurable

- README.rst
I think the BMW service is called "ConnectedDrive", not "Connected Driver"
Also removed some periods that seemed strange to me.
Added a note so that people don't forget to put their model year in the title of the issue.
> Fix some typos in README.rst

- bimmer_connected/state.py
- bimmer_connected/vehicle.py
- test/test_state.py
- test/test_vehicle.py
- tox.ini
**check control messages**
Added property `has_check_control_messages` to `VehicleState`. This should work without understanding the data from the check control messages. See also #55 
**drive train attributes**
I added the property  `drive_train_attributes` to the `ConnectedDriveVehicle` class. This way you can figure out which attributes exist in the state, depending on the type of the vehicle. This should come handy in #41.
> added function for check_control messagages, but data is not yet parsed

- bimmer_connected/state.py
- bimmer_connected/vehicle.py
- test/__init__.py
- test/test_state.py
- test/test_vehicle.py
As discussed for quite some time :clock1: , I added the function  `available_attributes` to `ConnectedDriveVehicle`.
Based on the `lscType` attribute (and some others) it lists all the attributes that should be available for a vehicle. This was basically a trial and error based on the examples we have collected so far.
I'm not really convinced that this is a good implementation right now...
ToDos:
> added function `available_attributes`

- bimmer_connected/account.py
- bimmer_connected/const.py
- bimmer_connected/remote_services.py
- bimmer_connected/state.py
- bimmer_connected/vehicle.py
- test/__init__.py
This hopefully fixes https://github.com/m1n3rva/bimmer_connected/issues/84
It seems the login url to the BMW server has changed:
old url: webapi/oauth/token
new_url: gcdm/oauth/token
This seems to have fixed it for me. Please test this also in North America 🌎  and China 🌏 , they might also have different urls...
> updated login url

- bimmer_connected/state.py
Currently the log will show errors every 5 minutes in case specific data is not found, see [this](https://github.com/home-assistant/home-assistant/issues/16631) HA issue.
This changes the logging from `error` to `debug` mode, so the log doesn't get flooded with this messages.
> Change logging

- bimmer_connected/state.py
- test/test_state.py
As we now have new data(https://github.com/m1n3rva/bimmer_connected/issues/55), we can also parse the Check Control Messages into Python objects.
I added a new class `Check_Control_Message` in `state.py` providing a nicer access to the data sent from the server. Also added tests for this...
> added parsing of CCM

- bimmer_connected/remote_services.py
- bimmer_connected/state.py
https://github.com/m1n3rva/bimmer_connected/issues/101#issue-435298664
Fixes #101 
This state is returned by the server when the sunroof lid when it's titled up rather than fully opened. Errors are raised when vehicle state is polled and the sunroof is in this position. This change addresses that problem.
> Fix issue 101, add OPEN_TILT to lid states in state.py

- requirements.txt
- setup.py
> Require typing only for Python < 3.5

- bimmer_connected/account.py
I find that (at least in my region), the Connected Drive servers can be pretty flaky sometimes and return a 500 error which will work with a retry 99% of the time.
This pull request adds the ability to configure this library to automatically retry HTTP 500 errors for the specified number of retries - although defaults to not doing this to preserve existing behavior.
Originally I'd done this in my code, but it's more reliable to do it in your library (if you're willing to accept this PR), as you have access to the HTTP response code. Otherwise I have to parse your error message and hope it stays the same or similar!
> Add ability to retry comms on HTTP 500 error

- bimmer_connected/account.py
- bimmer_connected/const.py
- bimmer_connected/country_selector.py
Fixes #150. 
Uses `customer.bmwgroup.com` for authentication. This should work for `rest_of_world` and `us`, as those URLs are defined in [https://customer.bmwgroup.com/one/app/oauth.js](https://customer.bmwgroup.com/one/app/oauth.js). 
For `china`, this needs to be tested by someone with a `china` vehicle. Workaround would be an additional condition to use the old authentication scheme (not implemented yet).
Many thanks @janhaa and @Timo47v for pointing this out!
@gerard33 could you please merge this (and then update the HA component as well)?
> Use customer.bmwgroup.com to get token

- bimmer_connected/state.py
Fixes #142 
Fixes #141 
Fixes #129 
Fix this log :
```shell
File "/usr/local/lib/python3.7/site-packages/bimmer_connected/state.py", line 307, in __getattr__
return self._attributes[item]
KeyError: '[the_key]'
```
Will need a release to f!x home-assistant/home-assistant#31704.
But first need a CI fix : `rrequirements.txt` not found ...
> Fix __getattr__ KeyError

- .travis.yml
- bimmer_connected/country_selector.py
- bimmer_connected/vehicle.py
- test/__init__.py
- test/responses/F31/status.json
- test/responses/vehicles.json
- test/test_account.py
- test/test_remote_services.py
- test/test_state.py
- test/test_vehicle.py
- tox.ini
Due to the new authorization endpoint, even more tests were failing. When trying to correct them, I fixed all.
Fixes #134. Many thanks to @timmccor for #136.
Only test for Python 3.5 still fails due to dictionaries not preserving order. But before using an OrderedDict, I'd rather remove support for Python 3.5.
> Fix all the tests (except py35)

- bimmer_connected/account.py
- bimmer_connected/const.py
Fixes #153. Apparently US still uses the old API, so only EU now uses ´customer.bmwgroup.com`.
Sorry for the hassle guys!
> Revert customer.bmwgroup.com for US/China

- bimmer_connected/cli.py
- bimmer_connected/vehicle.py
- test/__init__.py
- test/test_vehicle.py
Fixes #139 and replaces #115.
Due to some merge conflicts I had to refactor @gps1539's SendPOI OSM code and while doing so implemented a abstract `Message` class that can be used for both standard messages (subject, 255-char message) or POIs.
> Send message to car & send POI from OSM

- bimmer_connected/cli.py
- bimmer_connected/remote_services.py
- bimmer_connected/vehicle.py
- test/__init__.py
- test/responses/G31_NBTevo/msg_executed.json
- test/test_remote_services.py
- test/test_vehicle.py
This PR provides the necessary refactoring to enable #165 in Home Assistant.
__WARNING!__ This is a breaking change as we're moving the `Message` and `PointOfInterest` classes from `vehicle.py` to `remote_services.py`, where they actually belong. 
The _cli_ is not affected by this change as it has has been adapted already.
See the implementation in `cli.py` on how to call `trigger_send_message` and `trigger_send_poi` correctly. Both require a `dict` as parameter with different keys.
> Refactor send_message and send_poi for HomeAssistant

- bimmer_connected/cli.py
- bimmer_connected/remote_services.py
- test/__init__.py
- test/test_remote_services.py
To comply with and enable the changes in home-assistant/core#33484, we need `snake_case` instead of `camelCase` parameters for `PointOfInterest`.
This is a potential **breaking change** for everybody who used `PointOfInterest` or `message.from_poi()` directly.
The cli parameters are interally adjusted and keep working.
> PointOfInterest parameters in snake_case

- README.rst
- bimmer_connected/cli.py
- docs/source/api/account.rst
- docs/source/api/country_selector.rst
- docs/source/api/remove_services.rst
- docs/source/api/state.rst
- docs/source/api/vehicle.rst
- docs/source/cli.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/readme.rst
- requirements-test.txt
Fixes #160.
Through the issue I had another view at our docs. This resulted in some changes to make them easier to read and contain more information: 
- Change theme from `alabaster` to `sphinx_rtd_theme`
- Include a documentation for `cli`
- For the automated parsing of `cli`, the `ArgumentParser` itself had to be refactored into its own function
- Improve navigation on the docs
- Improve `README.rst` to better integrate into docs and provide better information in GitHub
> General enhancement of docs, add cli documentation

- bimmer_connected/__init__.py
- bimmer_connected/version.py
- docs/source/conf.py
- requirements-test.txt
- setup.cfg
- setup.py
This PR adds [pbr](https://docs.openstack.org/pbr/latest/index.html) for automatically setting the correct library version based on the latest `git tag`. 
- if the latest commit also is referenced by a __tag__, the tag is taken as version number, i.e. `0.7.5`.
- if the latest commit has no tag, the main version will point to the latest **tag**, and then dev**number of commits after the tag**, i.e. `0.7.5dev1`.
This PR is an alternative to #172 which does not need any additional packaged files.
Although not tested with Github Actions, it should work flawlessly as well. If executed on a repository with a tag on the last commit (like we do when creating releases), running `python setup.py sdist bdist_wheel` (such as in the Action) creates the correctly versioned archives.
> Use pbr for build & versioning

- bimmer_connected/account.py
- bimmer_connected/cli.py
This PR stores the data of a fingerprint command in the home dir. Currently it's written to the `/usr/` dir which is not logic and can give issues if the user doesn't have write rights for that dir.
It will now change to
On Linux -> `/home/username/vehicle_fingerprint/<date-time>`
On Windows -> `C:\Users\username\vehicle_fingerprint\<date-time>`
This PR replaces #118 as that one had some conflicts.
> Use home dir for fingerprint data

- bimmer_connected/cli.py
- bimmer_connected/remote_services.py
- test/test_remote_services.py
Fixes #182. Many thanks to @droneando for doing inital testing and development!
Adds `VEHICLE_FINDER` remote service to trigger an update of the vehicle position.
Can be called from anywhere, no GPS coordinates required for vehicles pre 7/2014.
Usage from HA requires an update to the component.
> Add VEHICLE_FINDER remote service

- bimmer_connected/state.py
Fixes #185 by setting `state` to a default value (`{}`) if a vehicle does not have a status.
Seems to do what is should do (see discussion in PR) but to test the component we need to release a beta to PyPi.
> Don't break if vehicle has no status

- test/test_state.py
This fixes the tests after #187 was merged. My bad for not looking at the tests...
The old tests expected an Error if no vehicle status is found which is not the case anymore. This also fixes coverage.
> Fix tests after not breaking at old vehicles

- bimmer_connected/state.py
The warnings give unnecessary log entries in HA
> Remove log warnings

- .github/workflows/pythonpublish.yml
- bimmer_connected/account.py
- bimmer_connected/const.py
- bimmer_connected/country_selector.py
- test/__init__.py
- test/test_account.py
The changes in 0.7.8 lead to users in China (and probably North America) not being able to login anymore.
Apparently China uses older credentials than rest_of_world. However with the old credentials and the new API, at least china and rest_of_world are working (north_america should be working as well).
- This PR fixes or closes issue: fixes #220 
- This PR is related to issue: #208
> Fix login issues in China

- bimmer_connected/all_trips.py
- bimmer_connected/charging_profile.py
- bimmer_connected/cli.py
- bimmer_connected/efficiency.py
- bimmer_connected/last_destinations.py
- bimmer_connected/range_maps.py
- bimmer_connected/state.py
- bimmer_connected/vehicle.py
- test/__init__.py
- test/test_vehicle.py
This PR adds code that checks for available `state` services from the base vehicles list. If one's car is to old to support e.g. `statistics`, calling the endpoint will return an empty list. However the additional network traffic/waiting time is unecessary.
Also, cars `conventional` engines seem not to be able to call the `efficiency` and `navigation` endpoints. In case of a conventional car, they even return `403` errors, rising exceptions.
__Please test this with your cars thoroughly, I don't know if another selection would be fitting better!__
@gerard33, @Markinus, @netdata-be, could you please verify this is working as expected?
> Select available state services from vehicles list

- bimmer_connected/account.py
- bimmer_connected/country_selector.py
BMW changed the login secrets... Again... They did it a couple of weeks back, but reverted. 
We're now using the new secrets for `north_america` and `rest_of_world`, as `china` is still using the old secrets.
- This PR fixes or closes issue: fixes #250 
- This PR is related to issue: 
@gps1539, @deluxestyle, @nichwang88: Could you please test this?
> Fix login for north_america and rest_of_world

- bimmer_connected/state.py
Closes #257 👋
chargingInductivePositioning and fuelPercent do not seem to be supported anymore.
Requires confirmation as this only seems to be confirmed on hybrid plugin vehicles (Mini Cooper S E Countryman All4 and Bmw 330e iPerformance).
Do not throw exception for unknown status attributes
> Do not throw exception for unknown status attributes

- bimmer_connected/vehicle.py
- bimmer_connected/vehicle_status.py
Fix the issue with error codes in Home Assistant when no status of `parkingLight` is available via BMW ConnectedDrive.
I had the issue with my car now as well. Updated the code and tested it locally and works, the parking_light binary sensor is no longer made in HA when it's not available in the BMW ConnectedDrive api and so no more errors in the log.
- This PR fixes or closes issue: fixes #163, #296
> Fix parkingLight issue

- bimmer_connected/account.py
- bimmer_connected/country_selector.py
Again thanks to @TA2k, login for `north_america` should be fixed now.
I cannot verify that the code actually works as calling `https://b2vapi.bmwgroup.us/webapi/v1/user/vehicles` returns a 500 internal server error without error messages.
This might be due to my account in north_america not having any cars assigned.
- This PR fixes or closes issue: fixes (partly) #298 
- This PR is related to issue: #299
> Fix My BMW login for north_america

- bimmer_connected/account.py
- bimmer_connected/const.py
- bimmer_connected/country_selector.py
- bimmer_connected/remote_services.py
Thanks to the amazing work of @TA2k, I was able to adjust to the new URLs and requests required for the new remote services API.
Some considerations:
- It seems only actual remote services have changed, but you never know how long other services are available
- This change is for `rest_of_world` only. Not sure if `north_america` uses the same type of API (and the host is currently unkown). `china` we're still not able to reproduce the login unfortunately.
- [x ] Bugfix (non-breaking change which fixes an issue)
- This PR fixes or closes issue: fixes #309
- This PR is related to issue: https://github.com/home-assistant/core/issues/53977, https://github.com/home-assistant/core/issues/54524, https://github.com/bimmerconnected/bimmer_connected/discussions/273
> Fix remote services in rest_of_world

- bimmer_connected/account.py
Double checked the logs and found that the BMW API expects the timestamp in **milliseconds local time** instead of **seconds UTC**.
When trying this out against the BMW API, the times are changing massively, probably solving the issues with the wrong time being reported by the API.
- This PR is related to issue: #353, https://github.com/bimmerconnected/ha_custom_component/issues/12
> Fix `charging_end_time` by sending local time in milliseconds

- bimmer_connected/vehicle_status.py
- test/test_vehicle_status.py
This fixes edge cases of being unable to parse the `fuelIndicator` for `chargingEndTime`. 
In some cases, when the timestamp was not able to be parsed correctly, `UnboundLocalError` could be raised.
Now, parsing is done in a separate function that is returned early if timestamp parsing fails.
- This PR fixes or closes issue:
- This PR is related to issue: https://github.com/home-assistant/core/issues/61567
> Separate function for parsing `charging_end_time`

- bimmer_connected/remote_services.py
- test/test_remote_services.py
Add the `CHARGE_NOW` service. Based on https://github.com/bimmerconnected/bimmer_connected/discussions/387, but cannot test due to not having an EV.
@Nhubbers: Are you able to try this out?
- This PR is related to issue: https://github.com/bimmerconnected/bimmer_connected/discussions/387
> Add CHARGE_NOW remote service

- bimmer_connected/account.py
- bimmer_connected/utils.py
This PR includes various changes to improve the flaky login/unauthorized situation:
* Add `-10s` offset when storing token expiry to mitigate timing issues on `/vehicles` endpoint
* Add retry strategy to `north_america`/`rest_of_world` login
* Sometimes the `/authenticate` endpoint does not seem to work correctly, happend to me in the Android app as well
- This PR fixes or closes issue: fixes #393
- This PR is related to issue: https://github.com/home-assistant/core/issues/63214
> Fix login unauthorized

- bimmer_connected/vehicle_status.py
- test/test_vehicle_status.py
Updates typing & NoneType handling for attributes with units (should be `Tuple`, but could be `None` if no data is availabe).
Should fix `TypeError: 'NoneType' object is not subscriptable` in the HA component.
- This PR fixes or closes issue: fixes #399 
> Fix typing & defaults for attributes with units

- bimmer_connected/remote_services.py
- test/responses/remote_services/eadrax_service_error.json
- test/test_remote_services.py
Adds `ExecutionState.ERROR` which seems to be returned if the BMW API has encountered an error (maybe unable to reach the car?).
Also raises a new Exception with the full response from BMW API to hopefully get an indication why it is happening.
- This PR fixes or closes issue: fixes #403 
> Add ExecutionState.ERROR and raise Exception if it occurs

- bimmer_connected/vehicle_status.py
- test/test_vehicle_status.py
For vehicles in `CHINA`, the vehicle location was slowly moving as the converstion from GCJ02 to WGS84 actually stored the converted data back to the originally referenced dictionary in `VehicleStatus`. 
- This PR fixes or closes issue: fixes #419 
> Don't store GCJ02 converted position to VehicleStatus

- bimmer_connected/account.py
- bimmer_connected/api/authentication.py
- bimmer_connected/api/client.py
- bimmer_connected/api/utils.py
- bimmer_connected/const.py
- bimmer_connected/vehicle/fuel_and_battery.py
- bimmer_connected/vehicle/location.py
- bimmer_connected/vehicle/models.py
- test/test_account.py
- test/test_api.py
- test/test_vehicle.py
- test/test_vehicle_status.py
Refactors the login flow (both username/password & refresh_token) to be based on `httpx.Auth`.
This enables reacting on `HTTP 401 Unauthorized` responses and then starting the login flow again. 
This should finally fix all timing issues whatsoever, especially the ones mentioned in #428.
Also includes a graceful handle for `HTTP 429 Too Many Requests` during the login process which have come up recently.
> Refactor auth flow

- bimmer_connected/vehicle/reports.py
Add status Critical for CheckControlStatus based on the below error I got today after a critical message.
```
Unexpected error fetching bmw_connected_drive data: 'Critical' is not a valid CheckControlStatus
ValueError: 'Critical' is not a valid CheckControlStatus
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
self.data = await self._async_update_data()
File "/config/custom_components/bmw_connected_drive/coordinator.py", line 56, in _async_update_data
await self.account.get_vehicles()
File "/usr/local/lib/python3.9/site-packages/bimmer_connected/account.py", line 79, in get_vehicles
existing_vehicle.update_state(vehicle_dict)
File …
```
> Add Critical as CheckControlStatus

- bimmer_connected/utils.py
- bimmer_connected/vehicle/location.py
- test/responses/G21/json_export.json
- test/test_deprecated_vehicle_status.py
- test/test_utils.py
- test/test_vehicle_status.py
Force all parsed datetime values to UTC.
Due to https://github.com/bimmerconnected/bimmer_connected/discussions/422#discussioncomment-2319519 we cannot use `datetime.datetime.strptime()` but build our own logic using `time.strptime().tm_gmtoff`.
- This PR fixes or closes issue: fixes #441 
> Force UTC in timestamps

- bimmer_connected/vehicle/reports.py
- test/responses/G01/state_WBA00000000DEMO04_0.json
- test/test_deprecated_vehicle_status.py
- test/test_vehicle.py
- test/test_vehicle_status.py
Ignores severity `LOW` for the number of check control messages (used for the HA binary sensor), but still keeps them available (for use in the binary sensor attributes).
- This PR fixes or closes issue: 
- This PR is related to issue: https://github.com/home-assistant/core/issues/74568
> Ignore severity `LOW` check control messages

- bimmer_connected/vehicle/__init__.py
- bimmer_connected/vehicle/const.py
- bimmer_connected/vehicle/fuel_and_battery.py
- bimmer_connected/vehicle/vehicle.py
- test/responses/I20/state_WBA00000000DEMO01_0.json
- test/test_account.py
- test/test_deprecated_vehicle.py
- test/test_deprecated_vehicle_status.py
- test/test_utils.py
- test/test_vehicle.py
- test/test_vehicle_status.py
Fixes doubled `remaining_range_total` on newer electric only vehicles.
As parsing had to be based on `DriveTrainType`, some refactoring had to be done (mainly moving `DriveTrainType` into a separate file to avoid circular imports).
While implementing, it became clear that we do not need a separate attribute for range extender cars, so I removed that as well.
- This PR is related to issue: https://github.com/home-assistant/core/issues/74703
> Fix `remaining_range_total` on new electric-only vehicles

- bimmer_connected/vehicle/reports.py
During some testing, I (or rather mypy) figured out a small typing issue.
> Fix CBS `due_date` typing

- bimmer_connected/account.py
- test/test_account.py
`MyBMWAccount.get_vehicles()` will by default get the vehicle list on initialization only. If new vehicles are added to your account, re-initialize `MyBMWAccount` or call `get_vehicles(force_init=True)`.
Access the `/vehicles` endpoint only on init to reduce number of calls (2 of 3 API calls with one car).
- This PR is related to issue: https://github.com/home-assistant/core/issues/78792, https://github.com/bimmerconnected/bimmer_connected/issues/485
> Reduce API calls

- .pre-commit-config.yaml
- bimmer_connected/account.py
- bimmer_connected/api/client.py
- bimmer_connected/api/utils.py
- bimmer_connected/cli.py
- bimmer_connected/models.py
- bimmer_connected/utils.py
- requirements.txt
- setup.py
- test/test_account.py
- test/test_api.py
Fingerprints are by default stored in memory, as suggested in https://github.com/home-assistant/core/pull/74871#discussion_r979521676.
At maximum, 10 responses are stored to generate unlimited memory usage. When retrieving the responses, the current store is cleared.
Fingerprint functionality in CLI still works as before (although file names have been adjusted).
- This PR is related to issue: https://github.com/home-assistant/core/pull/74871
> Store fingerprint responses in memory instead of writing files

- .github/workflows/test.yml
- .pre-commit-config.yaml
- README.rst
- bimmer_connected/account.py
- bimmer_connected/api/client.py
- bimmer_connected/api/utils.py
- bimmer_connected/vehicle/location.py
- bimmer_connected/vehicle/remote_services.py
- bimmer_connected/vehicle/reports.py
- bimmer_connected/vehicle/vehicle.py
- bimmer_connected/vehicle/vehicle_status.py
- requirements-test.txt
- setup.cfg
- test/test_account.py
- test/test_deprecated_vehicle_status.py
- test/test_utils.py
- test/test_vehicle_status.py
Python 3.6 dropped out of official support in December 2021, so we're removing it from our tests. The current version should still work in Python 3.6, however our automated tests won't find any regressions (and we won't fix them for Python 3.6).
- Drop Python 3.6 tests in accordance to https://devguide.python.org/versions/
- Add support for Python 3.11
- This PR fixes or closes issue: fixes #494 
> Support Python 3.11, drop tests for Python 3.6

- bimmer_connected/cli.py
For convenience it would be nice to have the possibility of triggering the horn via cli. Same as it's possible to flash the lights via cli or app it should be possible to horn via cli or app.
I added the function to the cli.py file the same way the light flashing is implemented.
Regarding tests: I haven't seen api-tests so i did not add unit tests for this functionality. If you point me to some example tests I can add them, too.
> Add horn to cli

- bimmer_connected/cli.py
- bimmer_connected/const.py
- bimmer_connected/models.py
- test/test_remote_services.py
Enforces that the `name` entity is always filled when sending POI to the vehicle.
- This PR fixes or closes issue: fixes #512 
> Add default value for `name` in sendpoi

- bimmer_connected/api/authentication.py
- bimmer_connected/api/client.py
- bimmer_connected/api/utils.py
- bimmer_connected/models.py
- test/test_account.py
- test/test_api.py
- test/test_remote_services.py
Prompted by https://github.com/home-assistant/core/pull/90274, this PR introduces two new exceptions: `MyBMWAuthException` (HTTP status codes 401 and 403) and `MyBMWAPIException` (all other HTTP error codes).
These two are replacing all `httpx.HTTPStatusError` exceptions that might be raised (i.e. a request was technically successful but has a 4xx or 5xx HTTP status code).
The `request.raise_for_status()` handlers in `MyBMWClient`, `MyBMWLoginClient` and `MyBMWLoginRetry` have been adjusted accordingly to use `handle_httpstattuserror()`.
Most changes originate from `MyBMWAuthentication._login_row_na()` and  `MyBMWAuthentication._login_row_china()` as the `try ... except` block was removed (this is now handled directly in `MyBMWLoginClient`.
While this is a change deep at the base of our …
> Update httpx error handler

- bimmer_connected/vehicle/climate.py
- bimmer_connected/vehicle/vehicle.py
- test/responses/G26/bmw-eadrax-vcs_v4_vehicles_state_WBA00000000DEMO02.json
- test/test_vehicle_status.py
This PR adds (if available on vehicle):
- climatization status (`HEATING`, `COOLING`, `STANDBY`, `INACTIVE`, `UNKNOWN`)
- end time of climatization
- True/False indicator if climatization is ON
- This PR is related to issue: #521
> Add climatization status

- .pre-commit-config.yaml
- bimmer_connected/vehicle/tires.py
- test/responses/G20/bmw-eadrax-vcs_v4_vehicles_state_WBA00000000DEMO03.json
- test/test_vehicle_status.py
As the API apparently has changed (or at least doesn't provide `targetPressure` on all cars), we now allow it to be null.
- This PR fixes or closes issue: fixes https://github.com/home-assistant/core/issues/92550
> Allow tire target pressure to be empty

- bimmer_connected/const.py
Change the APP_VERSIONS Regions.CHINA to "3.1.0(20658)"
Version 3.3.1(22418) cannot work under China's API, the interface will return a 422 error. This will break the normal functioning of the refresh token, and also disrupt the login process (if someone has customized the logic for generating the x-login-nonce).
> Changes Regions.CHINA APP_VERSIONS to 3.1.0

- bimmer_connected/api/authentication.py
- bimmer_connected/api/regions.py
- bimmer_connected/api/utils.py
- bimmer_connected/const.py
- test/responses/auth/auth_cn_login_pwd.json
- test/responses/auth/auth_slider_captcha.json
- test/responses/auth/auth_slider_captcha_check.json
- test/responses/auth/auth_token.json
- test/test_account.py
Add a new nonce algorithm for the China region login, automatically complete the login graphic verification code, restore the login function for the China region, and update the refresh token method.
Due to the public disclosure of the x-login-nonce algorithm in the Chinese region, the logic has been added to the library. Currently, password login requires a graphical captcha.
The solution we have incorporated allows for automatic bypassing of the graphical captcha obtained from https://gitee.com/cvnc/BMW/blob/master/lib/BMWLogin.js
The refresh token also needs to be included in the header with the x-login-nonce encoded using `gcid`.
- This PR fixes or closes issue: fixes #504
> China login

- bimmer_connected/vehicle/vehicle.py
Mark `vehicle.is_vehicle_active` as deprecated to avoid confusion, as it no longer returns the inMotion status, as well as explain in docs it always returns False. Users might not notice that this function always returns False.
However, if you are working on bringing this functionality back, feel free to close this PR.
- This PR is related to issue:  https://github.com/bimmerconnected/bimmer_connected/issues/523
> Change is_vehicle_active to deprecated

- bimmer_connected/api/authentication.py
- bimmer_connected/api/utils.py
- bimmer_connected/models.py
- bimmer_connected/utils.py
- test/test_account.py
This PR updates our API client to handle not directly resolvable quota issues with a new exception (`MyBMWQuotaError`).
Additional logic was needed, as sometimes this error not only occurs with HTTP status code 429, but also 403 Forbidden.
After this is merged, we can update the HA component to not require re-entering the password on quota issues (see 
- This PR is related to issue: https://github.com/home-assistant/core/issues/85962
> Handle quota exceeded in HTTP 403

- bimmer_connected/models.py
- test/test_remote_services.py
Send all the entries to the MyBMW API when calling `send-to-car`. Especially important is the `formattedAddress` which if not given or an empty string will cause the API to respond with HTTP 500 error.
> Add required fields for sendpoi

- .pre-commit-config.yaml
- bimmer_connected/vehicle/remote_services.py
- test/__init__.py
- test/common.py
- test/conftest.py
- test/test_account.py
- test/test_api.py
- test/test_deprecated_vehicle.py
- test/test_deprecated_vehicle_status.py
- test/test_remote_services.py
- test/test_utils.py
- test/test_vehicle.py
- test/test_vehicle_status.py
This PR tries to clean up tests.
We now use a conftest.py and pytest fixture for all our API calls (as in the Home Assistant tests).
While at it, the vehicle state inside a test function can now be updated (e.g. by remote service sideeffects), so we can check if remote service changes actually change the vehicle state.
While this is not so important in the lib, this is a major step that could be used in HA testing (change switch, execute remote service, check HA final state).
For this to work we probably have to move our tests inline, i.e. deploy them with the library (not in scope of this PR).
Also found and fixed an issue where pre-climatization could never be turned off using our remote service.
> Refactor tests to conftest, add stateful tests for remote services

- .github/workflows/test.yml
- bimmer_connected/__init__.py
- bimmer_connected/api/authentication.py
- bimmer_connected/api/utils.py
- bimmer_connected/vehicle/location.py
- requirements.txt
- setup.cfg
- setup.py
- Add Python 3.12 as test environment for Github Actions
- Add classifier for Python 3.12
- Fix deprecations
- Replace `pkg_resources` with `importlib.metadata` / `importlib_metadata` (for < 3.8)
- Replace `datetime.utcnow()` with `datetime.now(tz=timezone.utc)`
- Replace `datetime.utcfromtimestamp(...)` with `datetime.fromtimestamp(..., tz=timezone.utc)`
> Add support for Python 3.12

- bimmer_connected/tests/test_vehicle.py
- bimmer_connected/vehicle/reports.py
- bimmer_connected/vehicle/vehicle.py
This enhancement adds headunit information like ID Drive generation and its current software revision.
Only vehicle data that also exists on older vehicles was used.
```Headunit(idrive_version='ID8', headunit_type='MGU', software_version='07/2023.35')```
> Add headunit data class also exposing current vehicle software version

- .pre-commit-config.yaml
- bimmer_connected/account.py
- bimmer_connected/tests/__init__.py
- bimmer_connected/tests/common.py
- bimmer_connected/tests/conftest.py
- bimmer_connected/tests/test_account.py
- bimmer_connected/tests/test_api.py
- bimmer_connected/tests/test_vehicle_status.py
- bimmer_connected/vehicle/vehicle.py
Adds exception handling, hopefully fixing some of the issues our users see if the API doesn't respond with the correct vehicle details (e.g. tire status) or an additional, non-functioning vehicle in the account.
> Add exception handling for unexpected responses

- README.rst
- bimmer_connected/api/authentication.py
- bimmer_connected/api/utils.py
- bimmer_connected/tests/test_account.py
- setup.cfg
- setup.py
Requires Pillow only for region china. This means it needs to be installed via `pip install bimmer_connected[china]`.
For chinese users, it will throw an error before the first login request against the API has been made and print a (hopefully) descriptive enough error message.
- This PR fixes or closes issue: fixes #579, fixes #582
> Require Pillow only in extra [china]

- bimmer_connected/account.py
- bimmer_connected/api/client.py
- bimmer_connected/cli.py
- bimmer_connected/tests/conftest.py
- bimmer_connected/tests/test_account.py
- bimmer_connected/tests/test_vehicle_status.py
- bimmer_connected/vehicle/fuel_and_battery.py
- bimmer_connected/vehicle/reports.py
- bimmer_connected/vehicle/vehicle.py
Removes the defunct `use_metric_units` parameter. The BMW API returns only metric values since 2022 anyways.
Remove parameter and don't confuse users with imperial units while the actual numbers are in metric units.
- This PR fixes or closes issue: fixes #581 
> Remove use_metric_units parameter

- bimmer_connected/models.py
- bimmer_connected/tests/test_remote_services.py
Fixes parsing of POI with numeric postcodes.
> Fix non-strings in sendpoi

- bimmer_connected/api/utils.py
- bimmer_connected/tests/test_api.py
Fixes VIN pseudonomization for vehicles not built in Germany (starting with `WB...`).
- This PR fixes or closes issue: fixes https://github.com/home-assistant/core/issues/105017
> Update VIN regex

- bimmer_connected/cli.py
- Disables default debug logging on CLI. Can be printed using `bimmerconnected --debug status ...`
- Adds option to return only one vehicle for status using `bimmerconnected status --vin VIN ...`
- This PR fixes or closes issue: fixes #594, fixes #589
> Disable default debug logging, allow status for one VIN only

- docs/source/development/fingerprints_in_homeassistant.rst
> Update docs on using the library fingerprints in HA

- setup.cfg
- setup.py
Saw a warning from pip when I tried to install `bimmer-connected[china]==0.14.6` (for Home Assistant).
```
WARNING: bimmer-connected 0.14.6 does not provide the extra 'china'
```
Turns out `pbr` has an open bug where `extras_require` inside `setup.py` are ignored. This changed moves them to `setup.cfg` so it is included in the sdist / wheel metadata.
This might fix #588.
https://bugs.launchpad.net/pbr/+bug/1931705
https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies
> Move extras_require to setup.cfg

- .github/workflows/test.yml
- .pre-commit-config.yaml
- bimmer_connected/tests/test_vehicle_status.py
- bimmer_connected/utils.py
- bimmer_connected/vehicle/climate.py
- bimmer_connected/vehicle/fuel_and_battery.py
- bimmer_connected/vehicle/vehicle.py
- pyproject.toml
- setup.py
Updates handling for time-only data when returned as da `datetime` object (currently only `charging_time_start`).
It is now created without timezone (`tzinfo=None`) and only works correctly if both the current timezone of the computer and the car are the same.
Unfortunatly the BMW API does not seem to provide any additional data to figure out which timezone is used for these values.
Time-only data where we have a number of minutes remaining (i.e. 250 seconds of climatization) are not impacted, as we can deterministically calculate those.
- This PR is related to issue: #616 (only fixed with HA update)
> Update timezone handling for time only data

- bimmer_connected/const.py
The charging statistics and charging sessions URLs have changed in April 2024. Although they are not yet used in this project, this is probably helpful for other projects to be aware of.
> Update of charging sessions and statistics URLs to v2

- bimmer_connected/account.py
- bimmer_connected/api/authentication.py
- bimmer_connected/cli.py
- bimmer_connected/tests/conftest.py
- bimmer_connected/tests/test_account.py
- bimmer_connected/tests/test_cli.py
Every CLI command now stores the API credentials in a file for reuse in later calls. By default, data is stored to `~/.bimmer_connected.json` (Mac and Linux) or `C:\Users\username\.bimmer_connected.json` (Windows). The file location can be changed using the `--oauth-store` parameter.
If you don't want the data stored, use the `--disable-oauth-store` parameter.
Store OAuth2 tokens from API for commandline calls so everybody not using Home Assistant does not have to go through a full reauthentication flow on every CLI command.
> CLI: Store OAuth credentials in local file

- .pre-commit-config.yaml
- bimmer_connected/tests/test_remote_services.py
- bimmer_connected/vehicle/remote_services.py
Don't check if `vehicleFinder` is active before triggering the remote service.
On older cars, this capability is returned as `false` but vehicle finder still works.
- This PR is related to issue: #642
> Ignore check for vehicle finder remote service

- bimmer_connected/models.py
- bimmer_connected/tests/responses/remote_services/eadrax_service_eventposition.json
- bimmer_connected/tests/test_remote_services.py
- bimmer_connected/tests/test_vehicle.py
Verify GPS position based on actual possible values (taken from https://github.com/home-assistant/core/blob/dff964582bb52882805b50a5f5bd235aab35e20b/homeassistant/helpers/config_validation.py#L136-L142).
- This PR fixes or closes issue: fixes #640
> Update GPS position verification

- bimmer_connected/vehicle/climate.py
There currently is no constant to reflect the "VENTILATION" state, resulting in it defaulting to "Unknown". It's the climatization function that's toggleable via the api while the car is off.
Currently there's no translation for VENTILATION, I'm new to contributions so I'm unsure if this is on the HA translation team or if this is something I have to add somewhere.
> Add VENTILATION climateControlState

- .pre-commit-config.yaml
- bimmer_connected/api/authentication.py
- bimmer_connected/api/utils.py
- bimmer_connected/tests/test_account.py
Always raise `MyBMWAuthError` when a HTTP error occurs during authentication.
This should solve retry loops due to quota issues like [here](https://github.com/home-assistant/core/issues/124464#issuecomment-2306719550) and trigger the HA reauthentication flow (stopping retries).
- This PR fixes or closes issue: fixes #https://github.com/home-assistant/core/issues/124464
> Always raise MyBMWAuthError during login

- bimmer_connected/account.py
- bimmer_connected/cli.py
- bimmer_connected/models.py
- bimmer_connected/tests/test_account.py
- bimmer_connected/tests/test_vehicle.py
Set observer position from positional arguments only for vehicle finder.
- This PR fixes or closes issue: fixes #644 
> CLI: Set observer position only for vehicle finder

- bimmer_connected/account.py
- bimmer_connected/api/authentication.py
- bimmer_connected/api/client.py
Allows passing in an external `httpx.VerifyType` (`Union[str, bool, ssl.SSLContext]`) via the `MyBMWAccount` constructor.
This is required to stop httpx from loading SSL certificates from disk when initializing a client, as this creates warnings since 2024.9 beta.
> ```
> 2024-09-01 11:35:33.553 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7f507d8c46d0>,) inside the event loop by integration 'bmw_connected_drive' at homeassistant/components/bmw_connected_drive/coordinator.py, line 61: await self.account.get_vehicles() (offender: /home/richard/home-assistant-core/venv/lib/python3.12/site-packages/httpx/_config.py, line 147: context.load_verify_locations(cafile=cafile)), please create a bug report at …
```
> Allow passing external SSL context

- README.rst
- bimmer_connected/account.py
- bimmer_connected/api/authentication.py
- bimmer_connected/cli.py
- bimmer_connected/const.py
- bimmer_connected/models.py
- bimmer_connected/tests/test_account.py
- bimmer_connected/tests/test_cli.py
- docs/source/_static/captcha_north_america.html
- docs/source/captcha.rst
- docs/source/conf.py
- docs/source/index.rst
BMW API for North America now requires a captcha to be solved. The token needs to be used during first init of `MyBMWAccount(..., hcaptcha_token=TOKEN)` or with the `--captcha-token` CLI parameter. See the [documentation](http://bimmer-connected.readthedocs.io/en/stable/captcha.html) for more information.
This does only apply when using the library outside Home Assistant.
Fix the login. Only required when not using the refresh_token flow.
Unfortunatly, this requires a manual intervention on the first login (or after any failed login attempt).
Once merged to master and a build is on readthedocs, I'll double check if the links are working as expected.
- This PR fixes or closes issue: fixes #661
- This PR is related to issue: https://github.com/home-assistant/core/issues/128598
> Handle captcha in North America

- README.rst
- docs/source/captcha.rst
- docs/source/captcha/north_america.rst
- docs/source/captcha/rest_of_world.rst
- docs/source/conf.py
Improves docs from feedback in discussions.
@gerard33 please check and let me know if you feel somethings missing.
- [s] Code quality improvements to existing code or addition of tests
> Improve Documentation for captcha

- bimmer_connected/models.py
- bimmer_connected/tests/common.py
- bimmer_connected/tests/test_remote_services.py
BMW API expects `lng` instead of `lon`.
- This PR fixes or closes issue: fixes #684
> Fix sendpoi

- bimmer_connected/cli.py
If an exception occured (e.g. connection issue or remote service issue), a new `refresh_token` was not saved to disk in CLI.
This PR ensures that tokens are saved.
> Ensure refresh token is stored

- bimmer_connected/utils.py
Allow running on some embedded Pythons again. cpython issue is only fixed in Python>=3.12.
This partly reverts commit 91c26e800133a33945caa620f7ea1ac1fd630f5d
- This PR fixes or closes issue: fixes #692 
> Fix embedded python datetime parsing

- .github/workflows/test.yml
- .pre-commit-config.yaml
- README.rst
- bimmer_connected/cli.py
- bimmer_connected/models.py
- bimmer_connected/tests/__init__.py
- bimmer_connected/tests/common.py
- bimmer_connected/tests/test_cli.py
- bimmer_connected/vehicle/fuel_and_battery.py
- bimmer_connected/vehicle/remote_services.py
- bimmer_connected/vehicle/reports.py
- pyproject.toml
Adds more rules to `ruff` and clean up pre-commit + test CI workflow.
> Improve linting & tests

- bimmer_connected/api/authentication.py
- bimmer_connected/api/client.py
- bimmer_connected/api/utils.py
- bimmer_connected/const.py
- bimmer_connected/tests/test_account.py
- bimmer_connected/vehicle/tires.py
- pyproject.toml
n/a
Added simple generic `x-user-agent` to prevent from being blocked ("quota exceeded").
BMW has apparently introduced a quota for HTTP requests, which are counted based on the HTTP header `x-user-agent`. Because this header key is hard-coded into the code and this integration is very popular, the server-side threshold may be exceeded under certain circumstances.
To prevent this, part of the `x-user-agent` is now generated dynamically. The same x-user-agent should now always be generated for each installation (server, container).
n/a
My home-assistant instance is running as an LXC using Proxmox Linux (ha-container with portainer). 
- first copy complete code from `bimmer_connected` on your LXC
- then mount the host volume to `/usr/local/lib/python3.13/site-packages/bimmer_connected` (in …
> Added simple generic x-user-agent to prevent from being blocked ("quota")
